name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "example.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.yingmale.win", custom_domain = true },
  { pattern = "quay.yingmale.win", custom_domain = true },
  { pattern = "gcr.yingmale.win", custom_domain = true },
  { pattern = "k8s-gcr.yingmale.win", custom_domain = true },
  { pattern = "k8s.yingmale.win", custom_domain = true },
  { pattern = "ghcr.yingmale.win", custom_domain = true },
  { pattern = "cloudsmith.yingmale.win", custom_domain = true },
  { pattern = "ecr.yingmale.win", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "yingmale.win"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
